name: Push new .NET PR to Main

on:
  workflow_dispatch:

  pull_request:
    types: [ "opened", "synchronize", "reopened" ]
    branches: [ "main" ]

jobs:
  ci-cd:
    permissions:
      security-events: write
    uses: TostCorp/.github/jobs/pr-closed-asp-net-app.yml
